name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hello, and welcome to the repository! 

            Thank you for opening your first issue here. We appreciate your contribution. Please make sure to follow our issue guidelines, and if you need any help, feel free to ask. We’re here to assist you! 😄

            Happy contributing!
          pr-message: |
            👋 Hi, thank you for submitting your first pull request! 

            We appreciate your effort and contribution to improving this project. The maintainers will review your pull request soon. In the meantime, make sure you’ve followed our contribution guidelines and completed all necessary checks.

            Thank you again for helping us grow! 🙌
